// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_option.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU7wGwI_Xh0gBe6-IA2ivasRe-3NT0QZQ',
    appId: '1:889059980934:web:ec09d1c4f9869299ae0307',
    messagingSenderId: '889059980934',
    projectId: 'hotel-booking-5e032',
    authDomain: 'hotel-booking-5e032.firebaseapp.com',
    storageBucket: 'hotel-booking-5e032.appspot.com',
    measurementId: 'G-P91C7SXLVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgWt0UYtXoYQ_ecM7cqIvxueXMcog0ol8',
    appId: '1:889059980934:android:af90d0f93ca9b382ae0307',
    messagingSenderId: '889059980934',
    projectId: 'hotel-booking-5e032',
    storageBucket: 'hotel-booking-5e032.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIy3b-N_SnZ0YApHycWvdrCO2DlJUKp2A',
    appId: '1:889059980934:ios:a47629d3fdca7080ae0307',
    messagingSenderId: '889059980934',
    projectId: 'hotel-booking-5e032',
    storageBucket: 'hotel-booking-5e032.appspot.com',
    iosClientId: '889059980934-fn3me4dp7cc5grj7kf50m7f1a0n5ao41.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIy3b-N_SnZ0YApHycWvdrCO2DlJUKp2A',
    appId: '1:889059980934:ios:a47629d3fdca7080ae0307',
    messagingSenderId: '889059980934',
    projectId: 'hotel-booking-5e032',
    storageBucket: 'hotel-booking-5e032.appspot.com',
    iosClientId: '889059980934-fn3me4dp7cc5grj7kf50m7f1a0n5ao41.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelApp',
  );
}
